feat: webhook supports headers
jeessy2/ddns-go pull request #626
Opened 2023-03-13 08:01 UTC by gutenye

# What does this PR do?

Add headers support for webhook

# Motivation

Some APIs use the `Authorization` header for authentication

# Additional Notes

<img width="774" alt="Screenshot 2023-03-13 at 15 59 54" src="https://user-images.githubusercontent.com/377544/224640887-5cdbc0ba-86b1-4a09-8cd7-3ea42a8e9da5.png">

2023-03-13 08:33 UTC, jeessy2 commented
header一般要加几个？

2023-03-13 08:38 UTC, gutenye commented
1个

2023-03-13 08:43 UTC, jeessy2 commented
那输入框默认1行，占位小点

2023-03-13 08:45 UTC, gutenye commented
Done

2023-05-06 11:44 UTC, CN-GuoZiyang commented
really need this!

2023-05-08 09:51 UTC, jeessy2 commented
> really need this!

等待 @gutenye 修改

2023-05-08 10:23 UTC, WaterLemons2k commented
> 等待 @gutenye 修改

修改什么？

2023-05-08 10:29 UTC, jeessy2 commented
> > 等待 @gutenye 修改
> 
> 
> 
> 修改什么？

review中的，问题不大

2023-05-09 03:58 UTC, WaterLemons2k commented on web/writing.html
> +                  <textarea class="form-control form" id="WebhookRequestHeaders" name="WebhookRequestHeaders" rows="1"
```suggestion
                  <input class="form-control form" id="WebhookRequestHeaders" name="WebhookRequestHeaders" value=""
```

@gutenye 我猜 @jeessy2 的意思是用 `input` 实现输入框默认1行（和 `URL` 一样）。

2023-05-09 12:32 UTC, gutenye commented
> 那输入框默认1行，占位小点

@jeessy2 已经[在这里](https://github.com/jeessy2/ddns-go/pull/626/commits/64fc827d4ae413bcbdff669be2b936865bf29cf7)改好了, `<textare rows="1">`就是默认1行, 比`<input>`更好, 可以手动缩放大小, 支持多行输入

2023-05-09 12:42 UTC, jeessy2 commented
> > 那输入框默认1行，占位小点
> 
> @jeessy2 已经[在这里](https://github.com/jeessy2/ddns-go/pull/626/commits/64fc827d4ae413bcbdff669be2b936865bf29cf7)改好了, `<textare rows="1">`就是默认1行, 比`<input>`更好, 可以手动缩放大小, 支持多行输入

就用textarea。其它参考改下

2023-05-09 12:54 UTC, gutenye commented
还要修改什么, 能说的详细点吗？

2023-05-09 13:08 UTC, WaterLemons2k commented
> 这里不是有吗，没注意看？ ![image](https://user-images.githubusercontent.com/6205259/237102950-eaf17c73-8709-490d-b3b9-6a279e34742a.png)

#663：

> 如果 review 后看到黄色的 Pending，记得点击 Review changes -> Submit review 来提交 review。

2023-05-09 13:25 UTC, gutenye commented
图片上看到的2个Pending已修改好了, 剩下的Pending看不见, 需要Submit review

2023-05-09 13:47 UTC, jeessy2 requested changes

2023-05-09 13:49 UTC, jeessy2 commented
> > 如果 review 后看到黄色的 `Pending`，记得点击 `Review changes` -> `Submit review` 来提交 review。

不点对方看不到😓

2023-05-10 05:23 UTC, gutenye commented
都改好了

2023-05-10 05:44 UTC, jeessy2 commented
页面上显示的`RequestHeaders `, 保存的实体又没`Request` 都统一下，要么都加，要么都不加？

2023-05-10 05:51 UTC, gutenye commented
> 页面上显示的RequestHeaders , 保存的实体又没Request 都统一下，要么都加，要么都不加？

Fixed in https://github.com/jeessy2/ddns-go/pull/626/commits/5aa4939b894d15788f37ffeb95bfd8f2da9e440c

2023-05-10 05:59 UTC, jeessy2 approved these changes
thanks @gutenye

2023-05-10 06:00 UTC, merged