feat: ip cache time configable
jeessy2/ddns-go pull request #708
Opened 2023-05-23 16:14 UTC by feranwq

# What does this PR do?
https://github.com/jeessy2/ddns-go/issues/706
# Motivation
可配置 IP 缓存次数,增加本地IP 检查频率, 且不会被服务商限流
# Additional Notes

2023-05-24 15:06 UTC, jeessy2 requested changes

2023-05-24 15:06 UTC, jeessy2 commented on main.go
> +var ipCacheTimes = flag.Int("t", 6, "IP缓存次数")
不用简写t。换个类似noweb的单词

2023-05-24 15:13 UTC, feranwq commented on README.md
> +- [可选] 支持启动带参数 `-l`监听地址 `-f`间隔时间(秒) `-t`缓存触发更新次数
好的,我看下一起改下

2023-05-25 03:00 UTC, jeessy2 commented
> @jeessy2 已更新, flag 改为 -cacheTimes , 说明没改, 下面举例说了一下用法, 默认示例里不再体现此参数

`缓存触发更新次数` 这个有点拗口，想个啥名称好点

2023-05-25 03:31 UTC, feranwq commented
> > @jeessy2 已更新, flag 改为 -cacheTimes , 说明没改, 下面举例说了一下用法, 默认示例里不再体现此参数
> 
> `缓存触发更新次数` 这个有点拗口，想个啥名称好点

间隔N次与服务商比对 怎么样

2023-05-25 03:38 UTC, jeessy2 commented
> > > @jeessy2 已更新, flag 改为 -cacheTimes , 说明没改, 下面举例说了一下用法, 默认示例里不再体现此参数
> 
> > 
> 
> > `缓存触发更新次数` 这个有点拗口，想个啥名称好点
> 
> 
> 
> 间隔N次与服务商比对 怎么样

可以

2023-05-25 05:45 UTC, feranwq commented
@jeessy2 done

2023-05-25 08:51 UTC, jeessy2 approved these changes
thanks @feranwq

2023-05-25 08:51 UTC, merged

2023-05-25 10:43 UTC, jeessy2 commented
还有一个转换问题，比如：输入的6，实际等待了5次，感觉有点不对呢

2023-05-25 15:07 UTC, feranwq commented
我试下，逻辑跟之前应该是没区别的

2023-05-25 15:27 UTC, jeessy2 commented
> 我试下，逻辑跟之前应该是没区别的

以前没暴露给用户看，所以不存在这个问题。现在让用户设置了，我设置的6，怎么间隔了5次

2023-05-25 16:03 UTC, jeessy2 commented
-cacheTimes间隔N次与服务商比对
看文字的话，应该是间隔的次数，设置6次，间隔应该也是6次
以前默认的5次，所以初始化应该是5次，间隔也是5次

2023-05-25 16:05 UTC, jeessy2 reviewed
我觉得应该这么改？

2023-05-25 16:05 UTC, jeessy2 commented on util/ip_cache.go
>  	if d.Addr != newAddr || d.Times <= 1 {
应该为d.Times <= 0

2023-05-25 16:05 UTC, jeessy2 commented on main.go
> +var ipCacheTimes = flag.Int("cacheTimes", 6, "间隔N次与服务商比对")
默认5次

2023-05-25 16:19 UTC, jeessy2 commented on util/ip_cache.go
>  	if d.Addr != newAddr || d.Times <= 1 {
那按你的来，默认5次